json_lt = '''
{
    "recordType": "",
    "bucketname": "",
    "application": "",
    "processId": "",
    "destinationBucket": "",
    "keepOriginalFile": "",
    "skipHeader": "",
    "includeFileHeader": "",
    "keepPartition": "",
    "includeTimestamp": "",
    "encryptFile": "",
    "datasetRegex": "",
    "outputPath": "",
    "jsonFormat": "",
    "addDateToFilename": "",
    "csvMode": "",
    "skipIdCreation": "",
    "copyFileToDatastore": "",
    "batchMode": "",
    "maxRetryAttempts": "",
    "lastRunMilliseconds": "",
    "generateFileId": "",
    "referenceTimeMilliseconds": "",
    "inPlaceProcess": "",
    "logDataAuditor": "",
    "recursiveCopy": "",
    "compressOutputAsGzip": "",
    "customPartition": "",
    "customPartitionIndex": "",
    "recordLength": ""
}
'''
